language: c

matrix:
  include:
  - os: linux
    sudo: required
    dist: trusty
    compiler: gcc
  - os: linux
    sudo: required
    dist: trusty
    compiler: clang
  - os: linux
    sudo: required
    dist: xenial
    compiler: gcc
  - os: linux
    sudo: required
    dist: xenial
    compiler: clang
  - os: osx
    sudo: required
    compiler: gcc
  - os: osx
    sudo: required
    compiler: clang

install:
  - make -C build-$(uname)
  - ./bake setup

script:
  - bake examples
  - bake examples --cfg release
  - bake list
  - bake clone SanderMertens/example
  - bake run example
  - bake run example --cfg release
  - bake new foo
  - bake run foo
  - bake run foo --cfg release

  
